### ISSUE TITLE
Error: Requires using expressions are not supported in examples.

### ISSUE THREAD

**Issue by carestad** [vue-styleguidist/vue-docgen-api#27]
Hi

I'm getting an error when trying to parse a Vue component that uses expressions in it's require, like so:

```javascript
this.svg.content = require(`!html-loader!${webRoot}/images/svg/${this.name}.svg`);
```

... and was advised by the script to file an issue here.

Is this possible to get by somehow?

I am using this to read SVG files and inject them into DOM, like explained here: http://calebporzio.com/using-inline-svgs-in-vue-compoments/

**Comment by rafaesc** [comment]
Hi @carestad,

Can you share the error return and the example of component?,

Regards

**Comment by BlitZz96** [comment]
https://ghostbin.com/paste/6tyq8
`                        <svg-icon
                            name="filter"
                            height="15px"
                            width="15px"
                        />`

Is there something else you need, @rafaesc ?

**Comment by MangeshPimpalkar** [comment]
+1

**Comment by MangeshPimpalkar** [comment]
Is there a way to ignore this error it has been more than 6 months this ticket is open.

**Comment by carestad** [comment]
> @carestad Were you able to find a alternative to this?

No I'm afraid not

**Comment by elevatebart** [comment]
Unfortunately, vue-docgen-api is very much basing its system on static analysis. 
Even more static than webpack.

`require` is mocked in order to allow for dynamic redesign of the component when we use the docgen in `vue-styleguidist`. You can have a look at [evalComponentCode.js](https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/evalComponentCode.js) to understand better what I need. 

The alternative I am offering is the one I use in my project:

```vue
<template>
  <FilterIcon height="15px" width="15px"/>
</template>
<script>
import FilterIcon from "@icons/filter.svg";

export default {
  components{
    FilterIcon
  }
}
</scritpt>
```

and loading the vue-svg-loader.

I am investigating how we could work around this limitation, but I can't promise anything until a more thorough analysis. Wish me luck as I dig in.

**Comment by elevatebart** [comment]
Hey andrew, I just created this branch where there is an example (basic) of what seems to work fine for me. [example loadicon](https://github.com/vue-styleguidist/vue-styleguidist/tree/example-loadicon)

Can you fork and show me what makes it break? I would like to help but am a little in the dark here.

**Comment by elevatebart** [comment]
Investigation in progress, report 1

This works
```vue
<template>
  <div v-html="require(`../svg/${iconName}.svg`)"></div>
</template>
<script>
export default {
	name: 'Icon',
	props: {
		iconName: String,
	},
};
</script>
```

While this does not
```vue
<template>
  <div v-html="icon"></div>
</template>
<script>
export default {
	name: 'Icon',
	props: {
		iconName: String,
	},
	computed: {
		icon() {
			return require(`../svg/${this.iconName}.svg`);
		},
	},
};
</script>
```

I still need to figure out what this error means.

**Comment by elevatebart** [comment]
I will close this now, since it seems not relevant anymore in v3
