### ISSUE TITLE
Scoped slot

### ISSUE THREAD

**Issue by KnaanBraz** [vue-styleguidist/vue-docgen-api#31]
Is it possible to get indication if slot is scoped?
Is it possible to add property to the slot for scope (like description)

**Comment by elevatebart** [comment]
Hello @KnaanBraz  ! Can you please install 3.1.0 or vue-styleguidist 3 and tell me if you still have the issue ?
We added support for binding on scoped slots but still do not exploit them in vue styleguidist.
If you would like to help I will be happy to guide you through the steps.

**Comment by stephsavoie** [comment]
I tried with vue-styleguidist v3.0.9 but it's not working:   the slot definition is simply ignored.

example that failed (tested using `Modal.vue` source component):
```
<template slot-scope="{item}">
  <div class="modal-footer">
    <!-- @slot Modal footer here -->
    <slot name="footer"></slot>
  </div>
</template>
```

**Comment by elevatebart** [comment]
Thanks @stephsavoie, I will add this test to the e2e. I hope to look at it this week.

**Comment by elevatebart** [comment]
Hello @stephsavoie , I believe that the template you gave is the usage of a scoped slot, not the slot itself. I added a scoped flag to slots so that you can know if it has bindings or not. 
If a slot has bindings, it is automatically scoping its content. This would give access insidde of your template to the content of the item.

See documentation here https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots
this is a scoped slot:
```html
<span>
  <slot v-bind:user="user">
    {{ user.lastName }}
  </slot>
</span>
```

and here is how one uses it:
```html
<current-user>
  <template v-slot:default="slotProps">
    {{ slotProps.user.firstName }}
  </template>
</current-user>
```

and a quick code sandbox to understand it better
https://codesandbox.io/embed/40mjwn311x?fontsize=14
